config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'pages#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Upmin::Engine => '/admin'
  end

  resources :transfers, only: [:new, :create]
  resources :users, only: [:edit, :update] do
    get :dashboard, on: :collection
    get :my_balances, on: :member
  end

  resources :transfers, only: [] do
    member do
      put :accept
      put :reject
    end
  end

  resources :orders, except: [:destroy] do
    resources :dishes, except: [:show] do
      get :copy, on: :member
    end
    member do
      put :change_status
      get :shipping
      put :finalize
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ACCEPTABLE_EMAILS = %w(codequest.com codequest.eu)

  has_many :orders
  has_many :user_balances, dependent: :destroy
  has_many :balances_as_payer, class_name: 'UserBalance', inverse_of: :payer, foreign_key: :payer_id
  has_many :submitted_transfers, inverse_of: :from, class_name: 'Transfer', foreign_key: :from_id
  has_many :received_transfers, inverse_of: :to, class_name: 'Transfer', foreign_key: :to_id

  after_create :add_first_balance

  scope :by_name, -> { order 'name' }

  devise :database_authenticatable, :rememberable, :trackable, :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(data)
    user = find_by(data.slice(:provider, :uid).to_h)
    if user.nil? && data.info.email.split('@')[1].in?(ACCEPTABLE_EMAILS)
      user = User.new({
                          provider: data.provider,
                          uid: data.uid,
                          name: data.info.name,
                          email: data.info.email
                      })
      user.save!
    end
    user
  end

  def balances
    @balances ||= UserBalance.balances_for(self)
  end

  def debts
    @debts ||= UserBalance.debts_to(self)
  end

  def add_first_balance
    user_balances.create balance: 0, payer: self
  end

  def subtract(amount, payer)
    return if self == payer && !substract_from_self
    user_balances.create balance: payer_balance(payer) - amount, payer: payer
  end

  def to_s
    name
  end

  def payer_balance(payer)
    user_balances.newest_for(payer.id).try(:balance) || Money.new(0, 'PLN')
  end

  def total_balance
    balances.map(&:balance).reduce :+
  end

  def total_debt
    debts.inject(Money.new(0,'PLN')) {|sum, debt| sum = sum+debt.balance}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(omniauth_params)
    if @user
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, kind: 'Google')
    else
      redirect_to root_path, alert: 'You must have an email at code quest'
    end
  end

  private

  def omniauth_params
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_filter :only_current_user, only: [:my_balances]

  def dashboard
    @order = Order.todays_order.try(:decorate)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to dashboard_users_path
    else
      redirect_to edit_user_path(@user)
    end
  end

  def my_balances
    @user = current_user
  end
  private

  def user_params
    params.require(:user).permit(:substract_from_self)
  end

  def find_user
    User.find(params[:id])
  end

  def only_current_user
    return if find_user == current_user
    redirect_to dashboard_users_path, alert: 'You can\' view others balances'
  end

end

app/views/users/_panel.html.slim
.clearfix
  - if user
    ul.login-list
      li.button = link_to 'Sign Out', destroy_user_session_path, method: 'delete'
    .right.panel-element
      ' #{user.total_balance} PLN
    .right.panel-element
      = link_to 'Settings', edit_user_path(user)
    .right.panel-element
      = link_to 'Finances', my_balances_user_path(user)
    .right.panel-element
      = link_to 'Dashboard', dashboard_users_path
  - else
    ul.login-list
      li.button = link_to 'Sign in with Google', user_omniauth_authorize_path(:google_oauth2)

app/views/users/dashboard.html.slim
h1 This is the user dashboard
.order-wrapper
  = link_to 'Past Orders', orders_path, class: 'button'
  - if @order
    = render partial: 'orders/summary', locals: {order: @order}
  - else
    h2 No order for today
    = link_to 'Add order', new_order_path, class: 'button'
  - if @order
    = render partial: 'orders/show', locals: {order: @order}

app/views/users/edit.html.slim
h1 Edit your account, #{@user.name}
= form_for @user do |f|
  .inner-wrapper.margin-bottom
    = f.label :substract_from_self, 'Substract payments from yourself (this is useful when you maintain a seperate account for payments)', class: 'inline'
    = f.check_box :substract_from_self, class: 'margin-left-small'
  = f.submit 'Update your account', class: 'button'

app/views/users/my_balances.html.slim
h2.margin-bottom Your balance is: #{@user.total_balance}
.margin-bottom
  = link_to 'New Transfer', new_transfer_path, class: 'button'
table
  thead
    tr
      th width="200" Who to
      th width="200" How Much
      th width="200" Last updated
  tbody
    - @user.balances.each do |balance|
      = render partial: 'user_balances/balance', locals: {user_balance: balance}
h2.margin-bottom People owe you
table
  thead
    tr
      th width="200" Who
      th width="200" How Much
      th width="200" Last updated
  tbody
    - @user.debts.each do |balance|
      = render partial:  'user_balances/debt', locals: {user_balance: balance}
    tr
      td Total
      td=@user.total_debt
      td


h2.margin-bottom Received Transfers
= render partial: 'transfers/table', locals: {transfers: @user.received_transfers.newest_first, column: :from, action: true}
h2.margin-bottom Submitted Transfers
= render partial: 'transfers/table', locals: {transfers: @user.submitted_transfers.newest_first, column: :to}