config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root 'pages#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Upmin::Engine => '/admin'
  end

  resources :transfers, only: [:new, :create]
  resources :users, only: [:edit, :update] do
    get :dashboard, on: :collection
    get :my_balances, on: :member
  end

  resources :transfers, only: [] do
    member do
      put :accept
      put :reject
    end
  end

  resources :orders, except: [:destroy] do
    resources :dishes, except: [:show] do
      get :copy, on: :member
    end
    member do
      put :change_status
      get :shipping
      put :finalize
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :dishes, dependent: :destroy

  before_create :ensure_one_order_per_day

  validates :user, presence: true
  validates :from, presence: true

  scope :past, -> { where.not(date: Date.today).order('date desc')}
  register_currency :pln
  monetize :shipping_cents

  enum status: [:in_progress, :ordered, :delivered]

  def self.todays_order
    find_by date: Date.today
  end

  def ensure_one_order_per_day
    return if Order.find_by date: Date.today
    true
  end

  def amount
    initial = Money.new(0, 'PLN')
    dishes.inject(initial) {|sum, dish| sum + dish.price }
  end

  def change_status!
    int_status = Order.statuses[status]
    if int_status < Order.statuses.count - 1
      self.status = int_status+1
      subtract_price if int_status == 1
      save!
    end
  end

  def subtract_price
    return if dishes_count == 0
    dishes.each do |dish|
      dish.subtract shipping/(dishes_count), user
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :assign_users, only: [:edit, :new]
  before_filter :find_order, except: [:new, :create, :index]

  def new
    @order = Order.new
  end

  def create
    @order = Order.new order_params.merge(date: Date.today)
    if @order.save
      redirect_to dashboard_users_path
    else
      redirect_to new_order_path, alert: @order.errors.full_messages.join(' ')
    end
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to dashboard_users_path
    else
      redirect_to edit_order_path(@order), alert: @order.errors.full_messages.join(' ')
    end
  end

  def change_status
    @order.change_status!
    redirect_to dashboard_users_path
  end

  def shipping
  end

  def index
    @orders = Order.past.decorate
  end

  private

  def assign_users
    @users = User.all.by_name.map do |user|
      [user.name, user.id]
    end
  end

  def order_params
    params.require(:order).permit(:user_id, :from, :shipping)
  end

  def find_order
    @order = Order.find params[:id]
  end
end

app/views/orders/_form.html.slim
- if @order.persisted?
  h1 Edit order
- else
  h1 New order
= form_for @order do |f|
  - selected = @order.user_id if @order.persisted?
  = f.label :user_id, 'Payer'
  = f.select :user_id, options_for_select(@users, selected)
  = f.label :from, 'Restaurant'
  = f.text_field :from, placeholder: 'Where are we ordering from?'
  = f.submit class: 'button'

app/views/orders/_order.html.slim
tr
  th= order.date
  th= order.user
  th= order.from
  th= order.shipping
  th= order.amount
  th= order.current_user_ordered?

app/views/orders/_show.html.slim
section.dishes
  - unless order.current_user_ordered?
    .row You haven't ordered anything yet
    .row
      = link_to 'Click here to order', new_order_dish_path(order), class: 'button'
section.others-dishes
  - if order.dishes.size > 0
    = render partial: 'dishes/table', locals: {dishes: order.dishes}
  - else
    .row No one else has been bothered to order.

app/views/orders/_summary.html.slim
section.orderer
  .row.light-weight Today <strong>#{order.user.name}</strong> pays.
  .row.light-weight We're ordering from: <strong>#{order.from}</strong>
  .row.light-weight The sum of the order (with shipping) is: <strong>#{order.amount+order.shipping}</strong>
  .row.light-weight Order status is: <strong>#{order.status.humanize}</strong>
  .row= order.summary_buttons

app/views/orders/index.html.slim
h1.margin-bottom These are past orders
table
  thead
    tr
      th width="200" Date
      th width="200" Orderer
      th width="200" Restaurant
      th width="200" Shipping
      th width="200" Total
      th width="200" Did I order
  tbody
    = render @orders

app/views/orders/shipping.html.slim
= form_for @order do |f|
  .row
    ' Total price of the order:
    span#order-total=@order.amount
  = f.label :shipping, 'Shipping Cost'
  = f.text_field :shipping
  .row
    ' Final Quota:
    span#total= @order.amount + @order.shipping
  = f.submit 'Add shipping', class: 'button'

javascript:
  var shippingInput = $('#order_shipping');
  var orderTotal = $('#order-total');
  updateTotal = function() {
    var shipping = parseFloat(shippingInput.val());
    var order = parseFloat(orderTotal.text());
    $('#total').text(shipping+order);
  };
  shippingInput.on('keyup', updateTotal);